version: "3.8"
services:
  app:
    build:
      context: .
    container_name: python_app
    env_file: .env
    ports:
      - "8500:8500"
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8500 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5439:5439"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      bash -c "docker-entrypoint.sh postgres &&
               psql -U ${POSTGRES_USER} -c 'CREATE DATABASE ${POSTGRES_TEST_DB}'"

volumes:
  postgres_data:
